import type { SaasLocale } from "../model"

const copy = {
  en: {
    title: "Chatbots",
    description:
      "Configure trusted assistants for this workspace and test every change before release.",
    newChatbot: "New chatbot",
    emptyTitle: "No chatbots yet",
    emptyBody: "Create the first bilingual assistant for your workspace knowledge.",
    loading: "Loading chatbots…",
    loadError: "Chatbots could not be loaded. Please try again.",
    readOnly: "Members can inspect and test chatbots. Owners and admins manage definitions.",
    createTitle: "Create chatbot",
    editTitle: "Edit chatbot",
    englishName: "English name",
    englishNameError: "Enter an English name.",
    russianName: "Russian name",
    russianNameError: "Enter a Russian name.",
    englishInstructions: "English instructions",
    russianInstructions: "Russian instructions",
    provider: "Provider",
    providerError: "Enter a lowercase provider name.",
    model: "Model",
    modelError: "Enter a valid model name.",
    sourceScope: "All workspace sources",
    create: "Create chatbot",
    save: "Save changes",
    saving: "Saving…",
    edit: "Edit",
    disable: "Disable",
    delete: "Delete",
    enabled: "Enabled",
    disabled: "Disabled",
    version: "Version",
    conflict: "This chatbot changed elsewhere. Reload it before editing again.",
    mutationError: "The chatbot change could not be completed. Please try again.",
    disableTitle: "Disable this chatbot?",
    disableBody: "New test conversations will be blocked until the chatbot is enabled again.",
    confirmDisable: "Confirm disable",
    deleteTitle: "Delete this chatbot?",
    deleteBody: "The chatbot will be archived and removed from the active workspace list.",
    confirmDelete: "Confirm delete",
    cancel: "Cancel",
  },
  ru: {
    title: "Чат-боты",
    description: "Настраивайте надёжных помощников и проверяйте изменения перед публикацией.",
    newChatbot: "Новый чат-бот",
    emptyTitle: "Чат-ботов пока нет",
    emptyBody: "Создайте первого двуязычного помощника для знаний рабочего пространства.",
    loading: "Загрузка чат-ботов…",
    loadError: "Не удалось загрузить чат-ботов. Повторите попытку.",
    readOnly:
      "Участники могут просматривать и тестировать чат-ботов. Настройки доступны владельцам и администраторам.",
    createTitle: "Создать чат-бота",
    editTitle: "Изменить чат-бота",
    englishName: "Название на английском",
    englishNameError: "Укажите название на английском.",
    russianName: "Название на русском",
    russianNameError: "Укажите название на русском.",
    englishInstructions: "Инструкции на английском",
    russianInstructions: "Инструкции на русском",
    provider: "Провайдер",
    providerError: "Укажите провайдера строчными буквами.",
    model: "Модель",
    modelError: "Укажите корректное имя модели.",
    sourceScope: "Все источники пространства",
    create: "Создать чат-бота",
    save: "Сохранить изменения",
    saving: "Сохранение…",
    edit: "Изменить",
    disable: "Отключить",
    delete: "Удалить",
    enabled: "Включён",
    disabled: "Отключён",
    version: "Версия",
    conflict: "Этот чат-бот изменён в другом месте. Перезагрузите его перед редактированием.",
    mutationError: "Не удалось изменить чат-бота. Повторите попытку.",
    disableTitle: "Отключить чат-бота?",
    disableBody: "Новые тестовые диалоги будут недоступны, пока чат-бот не включат снова.",
    confirmDisable: "Отключить",
    deleteTitle: "Удалить чат-бота?",
    deleteBody: "Чат-бот будет архивирован и исчезнет из активного списка.",
    confirmDelete: "Удалить",
    cancel: "Отмена",
  },
} as const

export function getChatbotsCopy(locale: SaasLocale): (typeof copy)[SaasLocale] {
  return copy[locale]
}
